file = open("biodata.txt","r+")
teks = file.read()
print(teks)
print("UPDATE DATA")
nama = input("Nama: ")
umur = input("Umur: ")
alamat = input("Alamat: ")
teks = "Nama:{}\nUmur: {}\nAlamat: {}\n".format(nama, umur, alamat)
file = open("biodata.txt", "r+")
file.write(teks)
file.close()
